"use client";
import { createContext, useContext, useEffect, useState } from "react";
import { usePathname } from "next/navigation";
import Link from "next/link";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowSquareOut, CaretRight, List, SignOut, ShieldCheck, Triangle, X, ArrowsClockwise } from "@phosphor-icons/react";
import type { AdminSession, BrokerCapability } from "@azuriya/api-types";
import { api, adminApi, APIError, errorMessage } from "@/lib/api";
import { navigation, routeLabel } from "@/lib/navigation";
import { ThemeSwitch } from "./theme";
import { Auth } from "./auth";
const SessionContext=createContext<AdminSession|undefined>(undefined);
export function useAdminSession() { const session=useContext(SessionContext);if(!session)throw new Error("Admin session required");return session; }
export function useCapability(capability:string) { return useAdminSession().capabilities.includes(capability as BrokerCapability); }
export function AdminShell({children}:{children:React.ReactNode}) {
 const client=useQueryClient(), path=usePathname(); const [drawer,setDrawer]=useState(false); const session=useQuery({queryKey:["admin","me"],queryFn:()=>adminApi<AdminSession>("/me"),retry:false});
 const logout=useMutation({mutationFn:()=>api("/auth/logout",{method:"POST",body:"{}"}),onSuccess:()=>{client.clear();client.setQueryData(["admin","me"],null);}});
 useEffect(()=>{const expire=()=>{client.clear();client.setQueryData(["admin","me"],null);};window.addEventListener("azuriya:admin-session-expired",expire);return()=>window.removeEventListener("azuriya:admin-session-expired",expire);},[client]);
 useEffect(()=>{setDrawer(false);},[path]);
 if(session.isPending)return <main className="loading"><div className="brand"><Triangle weight="fill"/>azuriya.</div><span className="spinner"/><p>Connecting to broker operations…</p></main>;
 if(session.error instanceof APIError && session.error.status===403)return <main className="loading"><ShieldCheck size={40}/><h1>Operations access required</h1><p>{errorMessage(session.error)}</p><button className="secondary" onClick={()=>logout.mutate()}>Sign out</button></main>;
 if(!session.data)return <Auth error={session.isError && (!(session.error instanceof APIError)||session.error.status!==401)?errorMessage(session.error):undefined}/>;
 return <SessionContext.Provider value={session.data}><div className="broker-shell">{drawer&&<button className="drawer-backdrop" aria-label="Close navigation" onClick={()=>setDrawer(false)}/>}<aside className={"sidebar "+(drawer?"is-open":"")}><Link className="brand" href="/dashboard"><Triangle weight="fill" size={27}/>azuriya<span>.</span></Link><button className="drawer-close round-tool" aria-label="Close navigation" onClick={()=>setDrawer(false)}><X size={18}/></button><div className="workspace-chip"><span className="workspace-emblem">A</span><div><strong>Broker workspace</strong><small>{session.data.user.role.toLowerCase()} access</small></div></div><nav aria-label="Broker navigation">{navigation.map(group=>{const items=group.items.filter(item=>session.data.capabilities.includes(item.capability as BrokerCapability));return items.length?<div className="nav-group" key={group.label}><span>{group.label}</span>{items.map(item=><Link key={item.href} href={item.href} className={path===item.href||(item.href==="/accounts"&&path.startsWith("/accounts/"))||(item.href==="/clients"&&path.startsWith("/clients/"))?"active":""} aria-current={path===item.href?"page":undefined}><item.icon size={19}/><span>{item.label}</span>{path===item.href&&<CaretRight size={14}/>}</Link>)}</div>:null;})}</nav><div className="sidebar-footer"><span className="status-dot"/>Native simulation<small>Tenant-scoped operations</small></div></aside><div className="app-main"><header className="topbar"><div className="breadcrumb"><button className="menu-tool round-tool" aria-label="Open navigation" onClick={()=>setDrawer(true)}><List size={20}/></button><span>Broker OS</span><CaretRight size={13}/><strong>{routeLabel(path)}</strong></div><div className="topbar-tools"><span className="simulation-label">SIMULATED</span><button className="round-tool" aria-label="Refresh canonical data" title="Refresh canonical data" onClick={()=>client.invalidateQueries({queryKey:["admin"]})}><ArrowsClockwise size={18}/></button><ThemeSwitch/><a className="round-tool" aria-label="Open trader terminal" title="Open trader terminal" href={process.env.NEXT_PUBLIC_TRADER_URL||"http://localhost:3000/terminal"} target="_blank" rel="noreferrer"><ArrowSquareOut size={18}/></a><span className="profile-avatar" title={session.data.user.email}>{session.data.user.email.slice(0,1).toUpperCase()}</span><button className="text-tool" aria-label="Sign out" title="Sign out" onClick={()=>logout.mutate()} disabled={logout.isPending}><SignOut size={20}/></button></div></header>{logout.isError&&<p className="error" role="alert">{errorMessage(logout.error)}</p>}<main className="page-content" id="content">{children}</main><footer className="app-footer"><span><ShieldCheck size={14}/>Native simulated execution</span><span>Server-authoritative values · Audited operations</span></footer></div></div></SessionContext.Provider>;
}

