"use client";
import type { Field } from "@/lib/profile-schema";
import { label } from "@/lib/format";
export function FieldGrid({fields,value,onChange,errors={},disabled=false}:{fields:readonly Field[];value:object;onChange:(patch:Record<string,unknown>)=>void;errors?:Record<string,string>;disabled?:boolean}) {
 const data=value as Record<string,unknown>;
 return <div className="form-grid">{fields.map(field=><div key={field.key} className={field.type==="boolean"?"full-width":undefined}>{field.type==="boolean"?<label className="checkbox-field"><input type="checkbox" checked={Boolean(data[field.key])} disabled={disabled} onChange={e=>onChange({[field.key]:e.target.checked})}/>{field.label}</label>:<label>{field.label}{field.type==="select"?<select value={String(data[field.key]??"")} disabled={disabled} required={field.required!==false} onChange={e=>onChange({[field.key]:e.target.value})}>{field.required===false&&<option value="">Inherit / no selection</option>}{field.options?.map(option=><option value={option} key={option}>{label(option)}</option>)}</select>:<input type={field.type==="email"?"email":field.type==="time"?"time":"text"} inputMode={field.type==="decimal"?"decimal":field.type==="integer"?"numeric":undefined} value={String(data[field.key]??"")} required={field.required!==false} disabled={disabled} maxLength={field.type==="decimal"?64:250} aria-invalid={Boolean(errors[field.key])} onChange={e=>onChange({[field.key]:field.type==="integer"?(e.target.value===""?"":Number(e.target.value)):e.target.value})}/>}</label>}{field.help&&<span className="field-help">{field.help}</span>}{errors[field.key]&&<span className="field-error" role="alert">{errors[field.key]}</span>}</div>)}</div>;
}
export function ReferenceSelect({label:valueLabel,value,onChange,options,disabled=false}:{label:string;value?:string;onChange:(value:string)=>void;options:{id:string;name:string}[];disabled?:boolean}) {return <label>{valueLabel}<select value={value||""} onChange={e=>onChange(e.target.value)} disabled={disabled}><option value="">Inherit platform / group policy</option>{options.map(option=><option key={option.id} value={option.id}>{option.name}</option>)}</select></label>;}

