"use client";
import { useState } from "react";
import { FloppyDisk, X } from "@phosphor-icons/react";
import type { BrokerProfile, ProfileKind, SessionWindow, LeverageRule, BrokerProfileSymbolOverride, BrokerInstrument, SymbolGroup } from "@azuriya/api-types";
import { useCommand, useResource } from "@/lib/admin-queries";
import { policyFields, profileCommand, profileResources, validatePolicy, createProfile, type Field } from "@/lib/profile-schema";
import { errorMessage } from "@/lib/api";
import { FieldGrid } from "./form-fields";
const metadataFields:Field[]=[{key:"name",label:"Profile name"},{key:"status",label:"Profile status",type:"select",options:["ACTIVE","DISABLED"]},{key:"description",label:"Description",required:false}];
const weekdays=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
export function PolicyEditor({source,onClose,canWrite}:{source:BrokerProfile;onClose:()=>void;canWrite:boolean}) {
 const [draft,setDraft]=useState(()=>structuredClone(source)),[reason,setReason]=useState(""),[errors,setErrors]=useState<Record<string,string>>({}),[saved,setSaved]=useState(false);
 const creating=!source.id,kind=draft.kind,key=kind.toLowerCase() as "pricing"|"commission"|"swap"|"leverage"|"margin"|"execution"|"session";
 const mutation=useCommand<BrokerProfile>("/"+profileResources[kind]+(creating?"":"/"+source.id),creating?"POST":"PATCH");
 const symbols=useResource<BrokerInstrument[]>("/symbols"),categories=useResource<SymbolGroup[]>("/symbol-groups");
 const disabled=!canWrite||mutation.isPending;
 const change=(patch:Partial<BrokerProfile>)=>{setDraft(value=>({...value,...patch}));setSaved(false);};
 const changePolicy=(patch:Record<string,unknown>)=>change({[key]:{...draft[key],...patch}});
 const windows=draft.session?.windows||[],rules=draft.leverage?.rules||[];
 return <section className="panel"><div className="panel-heading"><div><h3>{creating?"Create":"Edit"} {kind.toLowerCase()} profile</h3><p>{creating?"New canonical policy":"Revision "+draft.revision+" · Existing assignments use this profile"}</p></div><button className="text-tool" aria-label="Close editor" onClick={onClose}><X size={18}/></button></div><form onSubmit={e=>{e.preventDefault();const invalid=validatePolicy(kind,draft[key]||{});if(!draft.name.trim())invalid.name="Profile name is required.";setErrors(invalid);if(Object.keys(invalid).length||!canWrite)return;mutation.mutate({body:profileCommand(draft,reason,creating)},{onSuccess:record=>{setDraft(record);setSaved(true);}});}}><FieldGrid fields={metadataFields} value={draft} onChange={change} errors={errors} disabled={disabled}/><div className="form-section"><h3>{kind==="COMMISSION"?"Commission terms":kind==="SESSION"?"Weekly market availability":kind==="SWAP"?"Financing terms":"Policy parameters"}</h3><p>Resolved and validated by the native trading core.</p><FieldGrid fields={policyFields[kind]} value={draft[key]||{}} onChange={changePolicy} errors={errors} disabled={disabled}/></div>
 {kind==="SESSION"&&<div className="form-section"><h3>Weekly windows</h3><p>A window ending before or at its start continues into the following day. End time accepts 24:00.</p>{windows.map((window,index)=><div className="row-editor session-row" key={index}><label>Weekday<select value={window.day} disabled={disabled} onChange={e=>changePolicy({windows:windows.map((item,i)=>i===index?{...item,day:Number(e.target.value)}:item)})}>{weekdays.map((day,index)=><option key={day} value={index}>{day}</option>)}</select></label><label>Start<input aria-label={"Window "+(index+1)+" start"} value={window.start} disabled={disabled} placeholder="09:00" onChange={e=>changePolicy({windows:windows.map((item,i)=>i===index?{...item,start:e.target.value}:item)})}/></label><label>End<input aria-label={"Window "+(index+1)+" end"} value={window.end} disabled={disabled} placeholder="17:00" onChange={e=>changePolicy({windows:windows.map((item,i)=>i===index?{...item,end:e.target.value}:item)})}/></label><label>Availability<select value={window.status} disabled={disabled} onChange={e=>changePolicy({windows:windows.map((item,i)=>i===index?{...item,status:e.target.value as SessionWindow["status"]}:item)})}>{["OPEN","CLOSE_ONLY","CLOSED"].map(status=><option key={status}>{status}</option>)}</select></label><button type="button" aria-label={"Remove window "+(index+1)} disabled={disabled} onClick={()=>changePolicy({windows:windows.filter((_,i)=>i!==index)})}><X size={18}/></button></div>)}<button className="secondary" type="button" disabled={disabled} onClick={()=>changePolicy({windows:[...windows,{day:1,start:"09:00",end:"17:00",status:"OPEN"}]})}>Add session window</button></div>}
 {kind==="LEVERAGE"&&<div className="form-section"><h3>Leverage rules</h3><p>Asset class rules apply first, then symbol categories, then explicit symbols.</p>{rules.map((rule,index)=>{const scope=rule.symbol?"symbol":rule.symbol_group_id?"symbol_group_id":"asset_class";return <div className="row-editor" key={index}><div className="row-editor-head"><strong>Rule {index+1}</strong><button type="button" disabled={disabled} onClick={()=>changePolicy({rules:rules.filter((_,i)=>i!==index)})}>Remove rule</button></div><div className="form-grid"><label>Rule scope<select disabled={disabled} value={scope} onChange={e=>changePolicy({rules:rules.map((item,i)=>i===index?{max_leverage:item.max_leverage,[e.target.value]:e.target.value==="asset_class"?"FOREX":""}:item)})}><option value="asset_class">Asset class</option><option value="symbol_group_id">Symbol category</option><option value="symbol">Explicit symbol</option></select></label><label>Rule target{scope==="asset_class"?<input disabled={disabled} value={rule.asset_class||""} onChange={e=>changePolicy({rules:rules.map((item,i)=>i===index?{asset_class:e.target.value,max_leverage:item.max_leverage}:item)})}/>:<select disabled={disabled} value={rule.symbol||rule.symbol_group_id||""} onChange={e=>changePolicy({rules:rules.map((item,i)=>i===index?{max_leverage:item.max_leverage,[scope]:e.target.value}:item)})}><option value="">Choose target</option>{scope==="symbol"?(symbols.data||[]).map(symbol=><option key={symbol.symbol}>{symbol.symbol}</option>):(categories.data||[]).map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select>}</label><label>Maximum leverage<input inputMode="decimal" value={rule.max_leverage} disabled={disabled} onChange={e=>changePolicy({rules:rules.map((item,i)=>i===index?{...item,max_leverage:e.target.value}:item)})}/></label></div></div>;})}<button className="secondary" type="button" disabled={disabled} onClick={()=>changePolicy({rules:[...rules,{asset_class:"FOREX",max_leverage:"100"}] as LeverageRule[]})}>Add leverage rule</button></div>}
 {["PRICING","COMMISSION","SWAP"].includes(kind)&&<div className="form-section"><h3>Symbol overrides</h3><p>Override this profile's terms for a named symbol; other symbols retain its default terms.</p>{(draft.symbol_overrides||[]).map((override,index)=><div className="row-editor" key={index}><div className="row-editor-head"><strong>Override {index+1}</strong><button type="button" disabled={disabled} onClick={()=>change({symbol_overrides:(draft.symbol_overrides||[]).filter((_,i)=>i!==index)})}>Remove override</button></div><label>Symbol<select value={override.symbol} disabled={disabled} onChange={e=>change({symbol_overrides:(draft.symbol_overrides||[]).map((item,i)=>i===index?{...item,symbol:e.target.value}:item)})}><option value="">Select symbol</option>{(symbols.data||[]).map(symbol=><option key={symbol.symbol}>{symbol.symbol}</option>)}</select></label><div className="form-section"><FieldGrid fields={policyFields[kind]} value={(override as unknown as Record<string,object>)[key]||{}} onChange={patch=>change({symbol_overrides:(draft.symbol_overrides||[]).map((item,i)=>i===index?{...item,[key]:{...(item as unknown as Record<string,object>)[key],...patch}}:item) as BrokerProfileSymbolOverride[]})} disabled={disabled}/></div></div>)}<button className="secondary" type="button" disabled={disabled} onClick={()=>change({symbol_overrides:[...(draft.symbol_overrides||[]),{symbol:symbols.data?.[0]?.symbol||"",[key]:structuredClone(createProfile(kind)[key])} as BrokerProfileSymbolOverride]})}>Add symbol override</button></div>}
 <div className="form-section"><label>Reason for change<textarea value={reason} onChange={e=>setReason(e.target.value)} required={canWrite} disabled={disabled} minLength={3} maxLength={1000} placeholder="Describe why these terms are changing."/></label></div>{mutation.isError&&<p className="error" role="alert">{errorMessage(mutation.error)}</p>}{saved&&<p className="success" role="status">Profile saved. Its assignments now resolve the committed revision.</p>}<div className="form-footer"><span>{saved?"Saved":canWrite?"Server validation applies before configuration changes.":"Read access only"}</span><div><button type="button" className="secondary" onClick={onClose}>Close</button>{canWrite&&<button className="primary" disabled={mutation.isPending}><FloppyDisk size={16}/>{mutation.isPending?"Saving…":creating?"Create profile":"Save profile"}</button>}</div></div></form></section>;
}

