"use client";
import type { BrokerProfile, ProfileRefs, ProfileKind, SymbolRule } from "@azuriya/api-types";
import { useResource } from "@/lib/admin-queries";
import { profileResources } from "@/lib/profile-schema";
import { ReferenceSelect } from "./form-fields";
const references:{kind:ProfileKind;key:keyof ProfileRefs;label:string}[]=[{kind:"PRICING",key:"pricing_profile_id",label:"Pricing profile"},{kind:"COMMISSION",key:"commission_plan_id",label:"Commission plan"},{kind:"SWAP",key:"swap_plan_id",label:"Swap plan"},{kind:"LEVERAGE",key:"leverage_plan_id",label:"Leverage plan"},{kind:"MARGIN",key:"margin_profile_id",label:"Margin profile"},{kind:"EXECUTION",key:"execution_profile_id",label:"Execution profile"},{kind:"SESSION",key:"trading_session_profile_id",label:"Trading session"}];
function ProfileReference({reference,value,onChange,disabled}:{reference:(typeof references)[number];value?:string;onChange:(value:string)=>void;disabled?:boolean}) {const query=useResource<BrokerProfile[]>("/"+profileResources[reference.kind]);return <div><ReferenceSelect label={reference.label} value={value} onChange={onChange} options={(query.data||[]).filter(profile=>profile.status==="ACTIVE")} disabled={disabled||query.isPending}/>{query.isError&&<span className="field-error">Unable to load profile choices.</span>}</div>;}
export function ProfileReferences({value,onChange,disabled}:{value:ProfileRefs;onChange:(patch:ProfileRefs)=>void;disabled?:boolean}) {return <div className="form-grid">{references.map(reference=><ProfileReference key={reference.key} reference={reference} value={value[reference.key]} onChange={value=>onChange({[reference.key]:value})} disabled={disabled}/>)}</div>;}
export function SymbolRulesEditor({rules,onChange,symbols,categories,disabled}:{rules:SymbolRule[];onChange:(value:SymbolRule[])=>void;symbols:{symbol:string}[];categories:{id:string;name:string}[];disabled?:boolean}) {return <div className="form-section"><h3>Category and symbol rules</h3><p>Explicit symbol rules follow category rules. Empty references inherit earlier policy layers.</p>{rules.map((rule,index)=><div className="row-editor" key={index}><div className="row-editor-head"><strong>Rule {index+1}</strong><button type="button" disabled={disabled} onClick={()=>onChange(rules.filter((_,i)=>i!==index))}>Remove rule</button></div><div className="form-grid"><label>Rule scope<select value={rule.symbol?"symbol":"symbol_group_id"} disabled={disabled} onChange={e=>{const {symbol,symbol_group_id,...refs}=rule;void symbol;void symbol_group_id;onChange(rules.map((item,i)=>i===index?{...refs,...(e.target.value==="symbol"?{symbol:symbols[0]?.symbol||""}:{symbol_group_id:categories[0]?.id||""})}:item));}}><option value="symbol_group_id">Symbol category</option><option value="symbol">Explicit symbol</option></select></label><label>Rule target<select value={rule.symbol||rule.symbol_group_id||""} disabled={disabled} onChange={e=>onChange(rules.map((item,i)=>i===index?{...item,...(rule.symbol?{symbol:e.target.value}:{symbol_group_id:e.target.value})}:item))}><option value="">Select a target</option>{rule.symbol?symbols.map(symbol=><option key={symbol.symbol}>{symbol.symbol}</option>):categories.map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select></label></div><div className="form-section"><ProfileReferences value={rule} onChange={patch=>onChange(rules.map((item,i)=>i===index?{...item,...patch}:item))} disabled={disabled}/></div></div>)}<button className="secondary" type="button" disabled={disabled} onClick={()=>onChange([...rules,{symbol:symbols[0]?.symbol||""}])}>Add symbol rule</button></div>;}

