"use client";
import { useState } from "react";
import { Plus } from "@phosphor-icons/react";
import type { BrokerProfile, ProfileKind, TradingGroup, SymbolGroup, BrokerInstrument } from "@azuriya/api-types";
import { useResource } from "@/lib/admin-queries";
import { createProfile, profileResources, type Field } from "@/lib/profile-schema";
import { time, label } from "@/lib/format";
import { useCapability } from "@/components/admin-shell";
import { PageHeader } from "@/components/page-header";
import { DataTable, TableFilters, Badge } from "@/components/data-table";
import { PolicyEditor } from "@/components/policy-editor";
import { ResourceEditor } from "@/components/resource-editor";
import { ProfileReferences, SymbolRulesEditor } from "@/components/profile-references";
export const routeKinds:Record<string,ProfileKind>={pricing:"PRICING",commissions:"COMMISSION",swaps:"SWAP",leverage:"LEVERAGE",margin:"MARGIN",execution:"EXECUTION",sessions:"SESSION"};
const profileDescriptions:Record<ProfileKind,string>={PRICING:"Executable bid and ask terms, spread bounds and symbol overrides.",COMMISSION:"Per-lot costs with an explicit per-side or round-turn charging basis.",SWAP:"Signed financing rates, rollover timing and bounded catch-up.",LEVERAGE:"Maximum leverage and asset, category or symbol caps.",MARGIN:"Margin-call thresholds and deterministic simulated stop-out policy.",EXECUTION:"Fixed native simulated latency and execution policy.",SESSION:"Timezone-aware weekly market availability and close-only windows."};
export function ProfilePage({kind}:{kind:ProfileKind}) {
 const resource=profileResources[kind],canWrite=useCapability(["LEVERAGE","MARGIN"].includes(kind)?"risk.write":"pricing.write");
 const query=useResource<BrokerProfile[]>("/"+resource),[search,setSearch]=useState(""),[status,setStatus]=useState(""),[editing,setEditing]=useState<BrokerProfile>();
 const rows=(query.data||[]).filter(row=>(!status||row.status===status)&&(!search||(row.name+" "+row.description).toLowerCase().includes(search.toLowerCase())));
 return <><PageHeader title={kind==="SESSION"?"Trading sessions":label(kind)+" profiles"} description={profileDescriptions[kind]} eyebrow="TRADING CONFIGURATION">{canWrite&&<button className="primary" onClick={()=>setEditing(createProfile(kind))}><Plus size={17}/>Create profile</button>}</PageHeader>{editing&&<div className="editor-space"><PolicyEditor key={editing.id||"new"} source={editing} onClose={()=>setEditing(undefined)} canWrite={canWrite}/></div>}<section className="panel table-panel"><div className="panel-heading"><div><h3>Configured profiles</h3><p>Assign these records to trading groups, categories or symbols.</p></div><small>{query.data?.length||0} profiles</small></div><TableFilters search={search} onSearch={setSearch} status={status} onStatus={setStatus} statuses={["ACTIVE","DISABLED"]} count={rows.length}/><DataTable rows={rows} rowKey={row=>row.id} pending={query.isPending} error={query.error} retry={()=>query.refetch()} empty="Create a policy profile to configure trading terms." columns={[{key:"name",label:"Profile",render:row=><div className="cell-primary">{row.name}<small>{row.description||label(row.kind)}</small></div>},{key:"status",label:"Status",render:row=><Badge value={row.status}/>},{key:"revision",label:"Revision",numeric:true,render:row=>row.revision},{key:"overrides",label:"Symbol overrides",numeric:true,render:row=>row.symbol_overrides?.length||0},{key:"updated",label:"Updated",render:row=>time(row.updated_at)},{key:"edit",label:"",render:row=><button className="table-action" onClick={()=>setEditing(row)}>{canWrite?"Edit profile":"View profile"}</button>} ]}/></section></>;
}
const groupFields:Field[]=[{key:"name",label:"Group name"},{key:"description",label:"Description",required:false},{key:"status",label:"Group status",type:"select",options:["ACTIVE","DISABLED"]}];
const categoryFields:Field[]=groupFields.slice(0,2);
const instrumentFields:Field[]=[{key:"symbol",label:"Symbol"},{key:"display_name",label:"Display name"},{key:"asset_class",label:"Asset class",type:"select",options:["FOREX","METAL","INDEX","CRYPTO"]},{key:"base_currency",label:"Base currency"},{key:"quote_currency",label:"Quote currency"},{key:"digits",label:"Price precision",type:"integer",min:0,max:10},{key:"tick_size",label:"Tick size",type:"decimal"},{key:"contract_size",label:"Contract size",type:"decimal"},{key:"min_quantity",label:"Minimum lots",type:"decimal"},{key:"max_quantity",label:"Maximum lots",type:"decimal"},{key:"quantity_step",label:"Lot step",type:"decimal"},{key:"default_leverage",label:"Default leverage",type:"decimal"},{key:"trading_status",label:"Trading permission",type:"select",options:["OPEN","CLOSE_ONLY","DISABLED"]}];
export function GroupsPage({categories=false}:{categories?:boolean}) {
 const resource=categories?"symbol-groups":"trading-groups",query=useResource<(TradingGroup|SymbolGroup)[]>("/"+resource),canWrite=useCapability(categories?"symbols.write":"groups.write"),symbols=useResource<BrokerInstrument[]>("/symbols"),categoryList=useResource<SymbolGroup[]>("/symbol-groups");
 const [search,setSearch]=useState(""),[editing,setEditing]=useState<TradingGroup|SymbolGroup>();
 const rows=(query.data||[]).filter(row=>!search||(row.name+" "+row.description).toLowerCase().includes(search.toLowerCase()));
 const create=()=>setEditing({id:"",tenant_id:"",name:"",description:"",revision:1,created_at:"",updated_at:"",...(categories?{}:{status:"ACTIVE",symbol_rules:[]})} as TradingGroup);
 return <><PageHeader title={categories?"Symbol categories":"Trading groups"} description={categories?"Group related instruments and apply shared policy references.":"Configure account policy assignments and ordered category or symbol rules."} eyebrow="TRADING CONFIGURATION">{canWrite&&<button className="primary" onClick={create}><Plus size={17}/>Create {categories?"category":"group"}</button>}</PageHeader>{editing&&<div className="editor-space"><ResourceEditor key={editing.id||"new"} title={categories?"Category configuration":"Trading group configuration"} path={"/"+resource+(editing.id?"/"+editing.id:"")} source={editing} fields={categories?categoryFields:groupFields} creating={!editing.id} canWrite={canWrite} onClose={()=>setEditing(undefined)}>{(draft,change)=><><div className="form-section"><h3>Policy assignments</h3><p>Empty assignments inherit the prior layer in the server resolution order.</p><ProfileReferences value={draft} onChange={change} disabled={!canWrite}/></div>{!categories&&<SymbolRulesEditor rules={(draft as TradingGroup).symbol_rules||[]} onChange={symbol_rules=>change({symbol_rules} as Partial<TradingGroup>)} symbols={symbols.data||[]} categories={categoryList.data||[]} disabled={!canWrite}/>}</>}</ResourceEditor></div>}<section className="panel table-panel"><div className="panel-heading"><h3>{categories?"Symbol category directory":"Trading group directory"}</h3><small>{rows.length} records</small></div><TableFilters search={search} onSearch={setSearch} count={rows.length}/><DataTable rows={rows} rowKey={row=>row.id} pending={query.isPending} error={query.error} retry={()=>query.refetch()} columns={[{key:"name",label:"Name",render:row=><div className="cell-primary">{row.name}<small>{row.description||"Server-managed policy scope"}</small></div>},{key:"status",label:categories?"Symbols":"Status",render:row=>categories?((row as SymbolGroup).symbols||[]).join(", ")||"None assigned":<Badge value={(row as TradingGroup).status}/>},{key:"revision",label:"Revision",numeric:true,render:row=>row.revision},{key:"updated",label:"Updated",render:row=>time(row.updated_at)},{key:"edit",label:"",render:row=><button className="table-action" onClick={()=>setEditing(row)}>{canWrite?"Configure":"View details"}</button>} ]}/></section></>;
}
export function SymbolsPage() {
 const query=useResource<BrokerInstrument[]>("/symbols"),categories=useResource<SymbolGroup[]>("/symbol-groups"),canWrite=useCapability("symbols.write");
 const [search,setSearch]=useState(""),[status,setStatus]=useState(""),[editing,setEditing]=useState<BrokerInstrument>();
 const rows=(query.data||[]).filter(row=>(!status||row.trading_status===status)&&(!search||(row.symbol+" "+row.display_name).toLowerCase().includes(search.toLowerCase())));
 return <><PageHeader title="Symbols" description="Native instrument specifications, trading permission and explicit policy overrides." eyebrow="TRADING CONFIGURATION">{canWrite&&<button className="primary" onClick={()=>setEditing({id:"",tenant_id:"",symbol:"",display_name:"",asset_class:"FOREX",base_currency:"EUR",quote_currency:"USD",digits:5,tick_size:"0.00001",contract_size:"100000",min_quantity:"0.01",max_quantity:"100",quantity_step:"0.01",default_leverage:"100",trading_status:"OPEN",revision:1,profile_overrides:{}})}><Plus size={17}/>Create symbol</button>}</PageHeader>{editing&&<div className="editor-space"><ResourceEditor key={editing.id||"new"} title="Instrument specification" path={"/symbols"+(editing.id?"/"+editing.symbol:"")} source={editing} fields={instrumentFields} creating={!editing.id} canWrite={canWrite} onClose={()=>setEditing(undefined)}>{(draft,change)=><><div className="form-section"><label>Symbol category<select value={draft.symbol_group_id||""} disabled={!canWrite} onChange={e=>change({symbol_group_id:e.target.value})}><option value="">No category</option>{(categories.data||[]).map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select></label><p className="field-help">Structural specification changes are rejected while positions or executable pending orders exist.</p></div><div className="form-section"><h3>Instrument policy overrides</h3><p>These references follow category and group policies.</p><ProfileReferences value={draft.profile_overrides||{}} onChange={patch=>change({profile_overrides:{...draft.profile_overrides,...patch}})} disabled={!canWrite}/></div></>}</ResourceEditor></div>}<section className="panel table-panel"><div className="panel-heading"><h3>Instrument directory</h3><small>Canonical native specifications</small></div><TableFilters search={search} onSearch={setSearch} status={status} onStatus={setStatus} statuses={["OPEN","CLOSE_ONLY","DISABLED"]} count={rows.length}/><DataTable rows={rows} rowKey={row=>row.symbol} pending={query.isPending} error={query.error} retry={()=>query.refetch()} columns={[{key:"symbol",label:"Symbol",render:row=><div className="cell-primary">{row.symbol}<small>{row.display_name}</small></div>},{key:"class",label:"Asset class",render:row=>row.asset_class},{key:"status",label:"Permission",render:row=><Badge value={row.trading_status}/>},{key:"precision",label:"Digits / tick",render:row=>row.digits+" / "+row.tick_size},{key:"lots",label:"Lots / step",render:row=>row.min_quantity+"–"+row.max_quantity+" / "+row.quantity_step},{key:"leverage",label:"Default leverage",numeric:true,render:row=>"1:"+row.default_leverage},{key:"edit",label:"",render:row=><button className="table-action" onClick={()=>setEditing(row)}>{canWrite?"Configure":"View details"}</button>} ]}/></section></>;
}

