import { SquaresFour, UsersThree, Wallet, SlidersHorizontal, ChartPieSlice, ListChecks, Bank, FileText, ShieldCheck, GearSix } from "@phosphor-icons/react";
export const navigation = [
 {label:"Workspace",items:[{href:"/dashboard",label:"Overview",icon:SquaresFour,capability:"broker.read"},{href:"/clients",label:"Clients",icon:UsersThree,capability:"clients.read"},{href:"/accounts",label:"Trading accounts",icon:Wallet,capability:"accounts.read"}]},
 {label:"Trading configuration",items:[{href:"/trading/symbols",label:"Symbols",icon:SlidersHorizontal,capability:"symbols.read"},{href:"/trading/categories",label:"Symbol categories",icon:ListChecks,capability:"symbols.read"},{href:"/trading/groups",label:"Trading groups",icon:UsersThree,capability:"groups.read"},{href:"/trading/pricing",label:"Pricing",icon:SlidersHorizontal,capability:"pricing.read"},{href:"/trading/commissions",label:"Commissions",icon:Bank,capability:"pricing.read"},{href:"/trading/swaps",label:"Swaps",icon:Bank,capability:"pricing.read"},{href:"/trading/leverage",label:"Leverage",icon:SlidersHorizontal,capability:"risk.read"},{href:"/trading/margin",label:"Margin",icon:ShieldCheck,capability:"risk.read"},{href:"/trading/execution",label:"Execution",icon:ListChecks,capability:"pricing.read"},{href:"/trading/sessions",label:"Trading sessions",icon:ListChecks,capability:"pricing.read"}]},
 {label:"Operations",items:[{href:"/risk/exposure",label:"Exposure",icon:ChartPieSlice,capability:"risk.read"},{href:"/risk/accounts",label:"Account risk",icon:ShieldCheck,capability:"risk.read"},{href:"/dealer/positions",label:"Positions",icon:ListChecks,capability:"dealer.read"},{href:"/dealer/orders",label:"Orders",icon:ListChecks,capability:"dealer.read"},{href:"/dealer/executions",label:"Executions",icon:ListChecks,capability:"dealer.read"},{href:"/finance/balance-operations",label:"Balance operations",icon:Bank,capability:"accounts.read"}]},
 {label:"Administration",items:[{href:"/reports",label:"Reports",icon:FileText,capability:"reports.read"},{href:"/audit",label:"Audit trail",icon:ShieldCheck,capability:"audit.read"},{href:"/settings",label:"Tenant settings",icon:GearSix,capability:"tenant.settings.read"}]}
];
export function routeLabel(path:string) { return navigation.flatMap(group=>group.items).find(item=>item.href===path)?.label || (path.startsWith("/accounts/")?"Account details":path.startsWith("/clients/")?"Client details":"Broker operations"); }

